- &opts
  clients: 20:201:20
  device: test/pybenchmarktarget/01
  period: 10

- &cppopts
  <<: *opts
  worker: tangobenchmarks.client.external.Worker

- benchmark: read_benchmark
  title: "python read benchmark"
  <<: *opts

- benchmark: write_benchmark
  title: "Python attribute write benchmark"
  clients: 4,8,16,32,64,128
  <<: *opts

- benchmark: event_benchmark
  title: "Python event subscription benchmark"
  <<: *opts

- benchmark: pipe_write_benchmark
  title: "Python pipe write benchmark"
  size: 256
  <<: *opts

- benchmark: pipe_read_benchmark
  title: "Python pipe read benchmark"
  <<: *opts

- benchmark: read_benchmark
  title: "python read benchmark with cpp client"
  worker_program: tg_benchmark_client_read
  <<: *cppopts

- benchmark: write_benchmark
  title: "Python attribute write benchmark with cpp client"
  clients: 4,8,16,32,64,128
  worker_program: tg_benchmark_client_write
  <<: *cppopts

- benchmark: event_benchmark
  title: "Python event subscription benchmark with cpp client"
  worker_program: tg_benchmark_client_event
  <<: *cppopts

- benchmark: pipe_write_benchmark
  title: "Python pipe write benchmark with cpp client"
  size: 256
  worker_program: tg_benchmark_client_pipe_write
  <<: *cppopts

- benchmark: pipe_read_benchmark
  title: "Python pipe read benchmark with cpp client"
  worker_program: tg_benchmark_client_pipe_read
  <<: *cppopts

- server_instance: PyBenchmarkTarget/rtest
  device_class: PyBenchmarkTarget
  target_device: test/pybenchmarktarget/01
  # host: localhost:10000
