- benchmark: readbenchmark
  title: "python read benchmark"
  clients: 20:201:20
  device: test/pybenchmarktarget/01
  period: 10

- benchmark: writebenchmark
  title: "Python attribute write benchmark"
  clients: 4,8,16,32,64,128
  device: test/pybenchmarktarget/01
  period: 10

- benchmark: eventbenchmark
  title: "Python event subscription benchmark"
  clients: 20:201:20
  device: test/pybenchmarktarget/01
  period: 10

- benchmark: pipebenchmark
  title: "Python pipe read/write benchmark"
  clients: 20:201:20
  device: test/pybenchmarktarget/01
  size: 256
  period: 10


- server_instance: PyBenchmarkTarget/rtest
  device_class: PyBenchmarkTarget
  target_device: test/pybenchmarktarget/01
  # host: localhost:10000
